### ISSUE TITLE
onchange 'src/**/*.{js,jsx}' -v -w -- babel-node src/index.jsx > dist/index.html

### ISSUE THREAD

**Issue by gertcuykens** [Qard/onchange#37] opened 2016-08-12 11:05 UTC
How do you get the output of the command you want to run in a file? 

`onchange 'src/**/*.{js,jsx}' -v -w -- babel-node src/index.jsx > dist/index.html`

The above will get the output from `onchange` instead of `babel-node src/index.jsx`

Tried `onchange 'src/**/*.{js,jsx}' -v -w -- (babel-node src/index.jsx > dist/index.html)` but gave me a error

**Comment by bfred-it** [comment] 2016-08-25 04:45
`>` is part of the shell and probably `onchange` doesn't use that to run commands. watchify uses [outpipe](https://www.npmjs.com/package/outpipe) for this functionality:

```sh
watchify main.js -dv -o 'uglifyjs -cm | gzip > bundle.js.gz'
```

**Comment by blakeembrey** [comment] 2016-08-25 06:00
I'm not sure that we'd need `outpipe` here, it serves the purpose of re-running the same CLI flow but `onchange` has always been about running just the command. Perhaps this needs to be a new option, but I'd need to understand the current issue a little better.

The pipe works for me, but the pipe won't be closing each time since it's being piped from `onchange` (which is receiving it's `stdout` and `stderr` from the specified command). For instance, running the example on the README and piping it into a file works exactly as expected, `onchange '**/*.js' -- echo '{{event}} to {{changed}}' > test.out` triggered:

```
change to cli.js
change to cli.js
```

However, you can see it'd just keep appending with each execution (which I believe is a feature currently, not a bug). If you want to re-run a certain flow each step, perhaps we can add a `-o` option. Any chance you can respond with what exactly you're trying to achieve?

**Comment by bfred-it** [comment] 2016-08-25 07:34
That's the point, `onchange` could change to run not just one but more commands. For example I was trying to run `xo && ava` but that wasn't possible. Outpipe would allow that and any other commands that work with `>`

**Comment by blakeembrey** [comment] 2016-08-25 07:49
I understand that, but I was asking @gertcuykens what his use-case was and what exactly wasn't working. It wasn't clear from the original post whether literally nothing worked, or it just didn't work as expected. For example, the output of `onchange` should be identical to `babel-node`, which is why I asked for more info.

On the `-o` feature, I love it and would love to add it. I definitely don't have a problem with it and understand the use-case.

**Comment by gertcuykens** [comment] 2016-08-25 12:02
Basicly what I wanted was if a file changes just render me a server html page. Inside index.jsx is a `console.log(HTML)` line that prints my server page html `babel-node src/index.jsx > dist/index.html` But index.html did contain the stdout from onchange not the `console.log(HTML)` from babel script. The workaround for me was create a `build.sh` script that had `babel-node src/index.jsx > dist/index.html` inside and then do `onchange 'src/**/*.{js,jsx}' -v -w -- build.sh` instead.

**Comment by bfred-it** [comment] 2016-08-25 14:16
@gertcuykens if it's a node app you can also use npm scripts instead of creating a separate file

**Comment by blakeembrey** [comment] 2016-08-30 06:56
@gertcuykens When you say it contained the `stdout` from `onchange` and not from the script, can you give an example? Is it the verbose mode output or something else?

**Comment by Qard** [comment] 2016-08-30 17:24
It's an issue with bash operation priority. The `>` symbol won't even *get* to onchange because bash will already have decided to do something else with it. The only way to do more complicated things like that is to do it indirectly through a bash file or an npm script, as already discovered.

**Comment by bfred-it** [comment] 2016-08-30 17:28
It's not the only way, I posted a solution used by browserify in the first comment

**Comment by Qard** [comment] 2016-08-30 17:36
That's not real bash. That's also indirect.

**Comment by bfred-it** [comment] 2016-08-30 18:10
Sure, but it's better than having to create a file, especially when the command is written on the fly in the cli or if you want Windows compatibility.

**Comment by Qard** [comment] 2016-08-30 20:31
With npm scripts, you don't need to create a new file. Not speaking against the outpipe idea, just clarifying my statements. 😉

**Comment by blakeembrey** [comment] 2016-12-02 20:42
Just implemented https://github.com/Qard/onchange/pull/44. If command is specified, it'll pipe the output from command into `-o`. If not, it just runs it directly using `exec`.

**Closed** 2016-12-02 21:08 UTC
Labels: enhancement
